export const LINKS = {
  MAIN_PAGE: "/",
  CATALOG: "/catalog",
  CANDLES: "/catalog/candles",
  AROMA_DIFFUSERS: "/catalog/aroma-diffusers",
  AROMA_SACHET: "/catalog/aroma-sachet",
  PERFUME: "/catalog/perfume",
  PRODUCT: "product",
  HISTORIES: "histories",
  ABOUT: "about",
  CONTACTS: "contacts",
  VK: "https://vk.com/miascorner",
  TELEGRAM: "https://t.me/mias_corner",
  PINTEREST: "https://ru.pinterest.com/mias_corner/",
  GMAIL: "miascorner.business@gmail.com",
};
